stages:
  - build
  - test
  
build project:
  stage: build
  image: node:16
  script: 
    - npm install
    - npm install -D @playwright/test
    # - npm install contentful
    - npx playwright install

test project:
  stage: test
  image: node:16
  script:
    - npm install
    - npm install -D @playwright/test
    # - npm install contentful
    - npx playwright install
    # run test script