stages:
  - build
  - test
  
build project:
  stage: build
  image: node:16
  script: 
    - npm install
    - npm install -D @playwright/test
    - npx playwright install
    - npx playwright install-deps

test project:
  stage: test
  image: node:16
  script:
    - npm install
    - npm install -D @playwright/test
    - npx playwright install
    - npx playwright install-deps
    - npm run dev & npx wait-on http://localhost:3000
    - npm run test